In [1]:
import csv
import os
from matplotlib import pyplot as plt
from scipy import stats
import numpy as np
import pandas as pd

In [2]:
clean_file = pd.read_csv("cleaned_data.csv", encoding = "ISO-8859-1")
clean_file.head()

,S. No.,Timestamp,GADE,Game,Platform,Hours,earnings,whyplay,League,streams,...,Degree,Birthplace,Residence,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,Not difficult at all,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,0.0,...,Bachelor (or equivalent),USA,USA,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,Somewhat difficult,Other,PC,8.0,I play for fun,having fun,NaN,2.0,...,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,Not difficult at all,Other,PC,0.0,I play for fun,having fun,NaN,0.0,...,Bachelor (or equivalent),Germany,Germany,Singleplayer,Accept,8,17,31.0,DEU,DEU
3,4,42052.06804,Not difficult at all,Other,PC,20.0,I play for fun,improving,NaN,5.0,...,Bachelor (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
4,5,42052.08948,Very difficult,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,having fun,NaN,1.0,...,High school diploma (or equivalent),USA,South Korea,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

In [3]:
js_file = pd.read_csv("GamingStudy_data_JS.csv", encoding = "ISO-8859-1")
js_file.head()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,...,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,...,USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,...,USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,...,Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,...,USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,...,USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

In [22]:
merged= pd.merge(clean_file, js_file, on =['Timestamp'], how ='left')
merged.head()
#merged["whyplay_y"].unique()



#cleaned_JS_df = merged[['S.No.'] = "S. No._x",
                   #   ['Timestamp'] = ]

,S. No._x,Timestamp,GADE_x,Game_x,Platform_x,Hours_x,earnings_x,whyplay_x,League_x,streams_x,...,Birthplace_y,Residence_y,Reference,Playstyle_y,accept_y,GAD_T_y,SWL_T_y,SPIN_T_y,Residence_ISO3_y,Birthplace_ISO3_y
0,1,42052.00437,Not difficult at all,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,0.0,...,USA,USA,Reddit,Singleplayer,Accept,1.0,23.0,5.0,USA,USA
1,2,42052.00680,Somewhat difficult,Other,PC,8.0,I play for fun,having fun,NaN,2.0,...,USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8.0,16.0,33.0,USA,USA
2,3,42052.03860,Not difficult at all,Other,PC,0.0,I play for fun,having fun,NaN,0.0,...,Germany,Germany,Reddit,Singleplayer,Accept,8.0,17.0,31.0,DEU,DEU
3,4,42052.06804,Not difficult at all,Other,PC,20.0,I play for fun,improving,NaN,5.0,...,USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0.0,17.0,11.0,USA,USA
4,5,42052.08948,Very difficult,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,having fun,NaN,1.0,...,USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14.0,14.0,13.0,KOR,USA

In [23]:
merged.columns

Index(['S. No._x', 'Timestamp', 'GADE_x', 'Game_x', 'Platform_x', 'Hours_x',
       'earnings_x', 'whyplay_x', 'League_x', 'streams_x', 'Narcissism_x',
       'Gender_x', 'Age_x', 'Work_x', 'Degree_x', 'Birthplace_x',
       'Residence_x', 'Playstyle_x', 'accept_x', 'GAD_T_x', 'SWL_T_x',
       'SPIN_T_x', 'Residence_ISO3_x', 'Birthplace_ISO3_x', 'S. No._y', 'GAD1',
       'GAD2', 'GAD3', 'GAD4', 'GAD5', 'GAD6', 'GAD7', 'GADE_y', 'SWL1',
       'SWL2', 'SWL3', 'SWL4', 'SWL5', 'Game_y', 'Platform_y', 'Hours_y',
       'earnings_y', 'whyplay_y', 'League_y', 'highestleague', 'streams_y',
       'SPIN1', 'SPIN2', 'SPIN3', 'SPIN4', 'SPIN5', 'SPIN6', 'SPIN7', 'SPIN8',
       'SPIN9', 'SPIN10', 'SPIN11', 'SPIN12', 'SPIN13', 'SPIN14', 'SPIN15',
       'SPIN16', 'SPIN17', 'Narcissism_y', 'Gender_y', 'Age_y', 'Work_y',
       'Degree_y', 'Birthplace_y', 'Residence_y', 'Reference', 'Playstyle_y',
       'accept_y', 'GAD_T_y', 'SWL_T_y', 'SPIN_T_y', 'Residence_ISO3_y',
       'Birthplace_ISO3_y'],
      dtype='object')

In [24]:
merged.drop(['S. No._y', 'GAD1',
       'GAD2', 'GAD3', 'GAD4', 'GAD5', 'GAD6', 'GAD7', 'GADE_y', 'SWL1',
       'SWL2', 'SWL3', 'SWL4', 'SWL5', 'Game_y', 'Platform_y', 'Hours_y',
       'earnings_y', 'whyplay_x', 'League_y', 'highestleague', 'streams_y',
       'SPIN1', 'SPIN2', 'SPIN3', 'SPIN4', 'SPIN5', 'SPIN6', 'SPIN7', 'SPIN8',
       'SPIN9', 'SPIN10', 'SPIN11', 'SPIN12', 'SPIN13', 'SPIN14', 'SPIN15',
       'SPIN16', 'SPIN17', 'Narcissism_y', 'Gender_y', 'Age_y', 'Work_y',
       'Degree_y', 'Birthplace_y', 'Residence_y', 'Reference', 'Playstyle_y',
       'accept_y', 'GAD_T_y', 'SWL_T_y', 'SPIN_T_y', 'Residence_ISO3_y',
       'Birthplace_ISO3_y'], inplace=True, axis =1)

In [25]:
merged.head()

,S. No._x,Timestamp,GADE_x,Game_x,Platform_x,Hours_x,earnings_x,League_x,streams_x,Narcissism_x,...,Birthplace_x,Residence_x,Playstyle_x,accept_x,GAD_T_x,SWL_T_x,SPIN_T_x,Residence_ISO3_x,Birthplace_ISO3_x,whyplay_y
0,1,42052.00437,Not difficult at all,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,NaN,0.0,1.0,...,USA,USA,Singleplayer,Accept,1,23,5.0,USA,USA,having fun
1,2,42052.00680,Somewhat difficult,Other,PC,8.0,I play for fun,NaN,2.0,1.0,...,USA,USA,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA,having fun
2,3,42052.03860,Not difficult at all,Other,PC,0.0,I play for fun,NaN,0.0,4.0,...,Germany,Germany,Singleplayer,Accept,8,17,31.0,DEU,DEU,having fun
3,4,42052.06804,Not difficult at all,Other,PC,20.0,I play for fun,NaN,5.0,2.0,...,USA,USA,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA,improving
4,5,42052.08948,Very difficult,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,NaN,1.0,1.0,...,USA,South Korea,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA,having fun

In [27]:
merged.columns = ['S. No.', 'Timestamp', 'GADE', 'Game', 'Platform', 'Hours',
       'earnings', 'League', 'streams', 'Narcissism', 'Gender',
       'Age', 'Work', 'Degree', 'Birthplace', 'Residence',
       'Playstyle', 'accept', 'GAD_T', 'SWL_T', 'SPIN_T',
       'Residence_ISO3', 'Birthplace_ISO3', 'whyplay']

In [28]:
merged.head()

,S. No.,Timestamp,GADE,Game,Platform,Hours,earnings,League,streams,Narcissism,...,Birthplace,Residence,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3,whyplay
0,1,42052.00437,Not difficult at all,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,NaN,0.0,1.0,...,USA,USA,Singleplayer,Accept,1,23,5.0,USA,USA,having fun
1,2,42052.00680,Somewhat difficult,Other,PC,8.0,I play for fun,NaN,2.0,1.0,...,USA,USA,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA,having fun
2,3,42052.03860,Not difficult at all,Other,PC,0.0,I play for fun,NaN,0.0,4.0,...,Germany,Germany,Singleplayer,Accept,8,17,31.0,DEU,DEU,having fun
3,4,42052.06804,Not difficult at all,Other,PC,20.0,I play for fun,NaN,5.0,2.0,...,USA,USA,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA,improving
4,5,42052.08948,Very difficult,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,NaN,1.0,1.0,...,USA,South Korea,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA,having fun

In [30]:
merged.to_csv('merged_js.csv')